### ISSUE TITLE
The Navigation Compass is a milk button, and doesn't work

### ISSUE THREAD

**Issue by ChristianNewton** [5newts/minecraft#1]
* **Platform**:  BOTH
* **Version**:  1.16.4 on Java, 1.16.100 on Bedrock
* **Server**:  Lobby
* **Severity**:  2

The navigation compass does not work (invalid menu) and is a milk bucket

**Comment by Kickingbird3** [comment]
Working on it by replacing lobby plugin

**Comment by ChristianNewton** [comment]
Super Fixed!
